---
- name: This is attemp1 file
  hosts: all
  become: true
  tasks:
  - name: Install Required Software
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apache2
      - build-essential
      - python3-dev
      - libmysqlclient-dev
      - mysql-server
      - mysql-client
      - php
      - php-mysql
      - libapache2-mod-php
      - php-cli
      - php-cgi
      - php-gd
      - python3-pymysql
      - python3-pip
      - python3-setuptools

  - name: Install the MySQL-python through pip
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - mysql
      - mysql-client
      - mysql-connector-python
